baseURL: "https://homelabtim.com/"
languageCode: "en-us"
title: "Timothy Smith"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "HomelabTim"
  description: Main website for Timothy Smith
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "HomelabTim" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Timothy Smith"
    subtitle: "Follow Me, Hire Me, or Learn with Me."
    content: "A versatile Systems Engineer with a strong background in cloud computing, system administration, and DevOps practices. I specialize in building and maintaining scalable, secure, and efficient IT environments that power modern businesses."
    image: /images/selfie.png
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://fileshare.homelabtim.com/s/resume/"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/HomelabTim/
        - icon: fab fa-youtube
          url: https://www.youtube.com/@HomelabTim?sub_confirmation=1
        - icon: fab fa-github
          url: https://github.com/HomelabTim
        - icon: fab fa-discord
          url: https://discord.com/users/917686720965787679
        - icon: fa-solid fa-mug-hot
          url: https://buymeacoffee.com/homelabtim

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/selfie.png"
    content: |-
      Hi everyone! I am Timothy Smith a dedicated and passionate technology enthusiast, I bring extensive experience in systems administration, cloud engineering, and DevOps to the table. I hold an Associate of Applied Sciences in General Studies and an Associate of Applied Sciences in Computer Information Systems from Southwest Texas Junior College. I am currently a full-time student pursuing a Bachelor of Science in Cybersecurity and Information Assurance from Western Governors University. 

      My technical expertise includes cloud computing, virtualization, networking, and documentation writing, utilizing tools such as AWS, Google Cloud Platform (GCP), VS Code, Git, and Docker. I am AWS Solutions Architect Associate certified and have successfully managed on-premises and cloud server infrastructures, ensuring optimal functionality and reliability.

      Professionally, I have held roles such as Head of Infrastructure at AI Media Group and Systems Engineer at Kasm Technologies, where I managed over 200 servers, administered Proxmox infrastructure, optimized AI workflows, and provided comprehensive end-user support. I have a proven track record of delivering exceptional customer satisfaction and maintaining detailed documentation of internal procedures.

      I am actively seeking new opportunities where I can contribute my skills and experience to a forward-thinking organization. If you are looking for a passionate and skilled Cloud & DevOps Engineer, I would love to connect and discuss potential opportunities.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - AWS
        - Azure AD
        - TCP/IP
        - Fortinet
        - Active Directory
        - Docker 
        - Kubernetes
        - Python
        - PowerShell
        - GitHub

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Systems Engineer II"
        company: "TSR Solutions"
        companyUrl: "https://www.tsrsolutions.com"
        date: "July 2024 - August 2024"
        featuredLink:
          enable: false
          name: "View Company Website"
          url: "https://example.com"
        info:
          enable: true
          content: Remote | Full-Time Employment
        content: |
          Managed IT operations for diverse clients using HaloITSM and ConnectWise. Administered and secured Active Directory, Microsoft 365, Azure AD, and Google Admin. Deployed virtual infrastructures with Datto RMM, configured FortiGate firewalls and VPNs, and optimized VoIP systems. Enhanced cybersecurity with ThreatLocker, Barracuda, and Sophos, and supported cloud apps like SharePoint and Mimecast.

      - job: "Head of Infrastructure"
        company: "AI Media Group"
        companyUrl: "https://aimg.io"
        date: "November 2023 - June 2024"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Remote | Contract Employment
        content: |
          As the Head of Infrastructure at AIMG, I lead the management of on-premises servers, focusing on updates, maintenance, and ensuring optimal functionality. My role involves maintaining server health, implementing upgrades, and overseeing overall server operations to support the organization's seamless functioning.

      - job: "Systems Engineer"
        company: "Kasm Technologies"
        companyUrl: "https://kasmweb.com"
        date: "March 2023 - October 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Remote | Contract Employment
        content: |
          As a systems engineer I have expertise in markdown language and GitLab, alongside JIRA for ticketing. I play a crucial role in the company's advertisement by creating and editing YouTube videos, designing thumbnails, and writing scripts. Additionally, developing software solutions to meet team needs, ensuring high reliability and performance standards through thorough testing and debugging.

      - job: "Computer Technician Intern"
        company: "Rogers Technology"
        companyUrl: "https://www.rogersts.com"
        date: "July 2021 - September 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: This was an on-site internship while in college located at San Antonio, Texas.
        content: |
          Diagnosing and resolving hardware and software problems in computer systems. I performed maintenance, repairs, and upgrades to ensure optimal performance. My responsibilities also include providing technical support and assistance to end-users, addressing their computing needs efficiently.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Associate of Applied Science - AAS, Computer and Information Systems"
        school:
          name: "Southwest Texas College"
          url: "https://www.swtjc.edu"
        date: "2021 - 2023"
        content: |-
          Achievements Earned:
            - Recognized as the outstanding student in Computer Information Systems
          
          Skills Earned:
            - Networking · VMware Server · Wireless Networking · JavaScript · Communication · Computer Hardware · Python (Programming Language) · Microsoft PowerPoint · VMWare ESXi · Server Administration · Docker · VMware vSphere · Cisco Networking · Linux · HTML5 · Virtualization · Virtual Private Network (VPN) · IP Networking · Microsoft Excel · Microsoft Word

      - title: "Associate of Arts - AA, General Studies"
        school:
          name: "Southwest Texas College"
          url: "https://www.swtjc.edu"
        date: "2019 - 2021"
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Projects"
    items:
      - title: HomelabTim YouTube Channel
        content: Since October 2021, I've managed the YouTube channel HomelabTim, creating tech tutorials, reviews, and guides. With over 800 subscribers, my WireGuard VPN setup video has garnered over 38,000 views.
        url: "https://www.youtube.com/@HomelabTim?sub_confirmation=1"
        image: /images/youtube.png
      - title: GitHub Repositories
        content: Since March 2023, I've been posting my repositories on GitHub and contributing to startup projects. My work focuses on Docker, Kubernetes, cloud infrastructure, source control management, and engaging with the developer community.
        url: "https://github.com/HomelabTim"
        image: /images/github.png
      - title: Portfolio Website
        content: Since October 2021, I've managed a Hugo-based portfolio website to showcase my tech projects and achievements. I use Markdown for detailed blog posts, highlighting my work and offering insights into various technologies. The site serves as a comprehensive platform for my tech contributions and experiences.
        url: "https://portfolio.homelabtim.com"
        image: /images/portfolio.png
      

  # projects
  projects:
    enable: true
    title: "Portfolio"
    items:
      - title: Deploying Passbolt
        content: The best open-source password manager for small businesses.
        image: /images/projects/passbolt.webp
        featured:
          name: View Portfolio
          link: https://portfolio.homelabtim.com/projects/passbolt/
        badges:
          - "Networking"
          - "Servers"
          - "Software"
          - "Virtualization"
        links:
          - icon: fas fa-globe
            url: https://www.passbolt.com
          - icon: fab fa-github
            url: https://github.com/HomelabTim

      - title: Installing ComfyUI on MacOS
        content: Tutorial for how to setup a ComfyUI instance on MacOS with the M2 chip.
        image: /images/projects/comfyui.jpg
        featured:
          name: View Portfolio
          link: https://portfolio.homelabtim.com/projects/comfyui/
        badges:
          - "AI"
          - "Servers"
          - "Tutorial"
          - "Software"
          - "Virtualization"
        links:
          - icon: fab fa-github
            url: https://github.com/comfyanonymous/ComfyUI
          - icon: fab fa-github
            url: https://github.com/HomelabTim

      - title: Unleashing the power of Hugo
        content: The open-source static site generator written in go.
        image: /images/projects/hugo.png
        featured:
          name: View Portfolio
          link: https://portfolio.homelabtim.com/projects/hugo/
        badges:
          - "Networking"
          - "Servers"
          - "Software"
          - "Virtualization"
          - "Web Development"
        links:
          - icon: fas fa-globe
            url: https://gohugo.io
          - icon: fab fa-github
            url: https://github.com/HomelabTim

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Ready to take your tech projects to the next level? With a passion for innovation and a proven track record in virtualization, networking, and more, I'm here to help bring your ideas to life. Let's connect and create something extraordinary together. Feel free to fill out this form—I'll respond as soon as possible.
    #btnName: Email Me
    #btnLink: mailto:smithtimothy233@protonmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xldrzpnj # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
